export const blogPosts = [
  {
    id: 1,
    title: "How to Convert a Canva Design into a Microsoft Word Template",
    description:
      "Learn how to convert Canva designs into functional Microsoft Word templates. This guide shows you the best methods for creating editable Word documents while maintaining your brand elements from Canva designs.",
    slug: "convert-canva-to-word",
    date: "April 14, 2025",
    author: "Daniel Thomas",
    readingTime: "5 min",
    category: "Conversions",
    featured: true,
    imagePath: "/canva-to-word.webp",
  },
  {
    id: 2,
    title: "Ultimate Guide to Microsoft Word Templates",
    description:
      "What is a Word Template? Explore the benefits, types, and implementation of Microsoft Word templates for your organization. Learn how templates can ensure consistency and save valuable time.",
    slug: "ultimate-guide-to-word-templates",
    date: "April 8, 2025",
    author: "Daniel Thomas",
    readingTime: "8 min",
    category: "Templates",
    featured: false,
    imagePath: "/template.webp",
  },
  {
    id: 3,
    title:
      "Fields and Repeating Data in Word: Best Practices for Business Templates",
    description:
      "Learn how to use Word's fields to transform static templates into dynamic, error-resistant tools. Master REF fields, document properties, and content controls to eliminate manual data entry and reduce costly errors.",
    slug: "fields-and-repeating-data-in-word",
    date: "July 24, 2025",
    author: "Daniel Thomas",
    readingTime: "12 min",
    category: "Templates",
    featured: false,
    imagePath: "/blog/waste.webp",
  },
  {
    id: 4,
    title: "Creating Word Templates for Legal Firms: Best Practices",
    description:
      "Learn how to create professional, efficient Word templates for legal firms. Discover best practices for reducing errors, ensuring consistency, and protecting client confidentiality with smart template design.",
    slug: "word-templates-for-legal-firms",
    date: "July 25, 2025",
    author: "Daniel Thomas",
    readingTime: "10 min",
    category: "Legal",
    featured: false,
    imagePath: "/blog/legal.webp",
  },
  {
    id: 5,
    title:
      "Google Docs vs Microsoft Word: Which Is Best for Enterprise Workflows?",
    description:
      "Compare Google Docs and Microsoft Word for enterprise use. Discover why many organisations migrate from Google Docs to Word for advanced features, compliance, automation, and scalability needs.",
    slug: "google-docs-vs-microsoft-word",
    date: "August 27, 2025",
    author: "Rochelle Robinson",
    readingTime: "12 min",
    category: "Comparison",
    featured: false,
    imagePath: "/blog/google-docs-or-word.webp",
  },
  {
    id: 6,
    title: "PDF to Word Conversion That Works for Business",
    description:
      "Discover why professional PDF to Word conversion matters for business. Learn about accuracy, security, and formatting challenges that free converters can't handle.",
    slug: "pdf-to-word-conversion",
    date: "October 3, 2025",
    author: "Aleisha Robinson",
    readingTime: "10 min",
    category: "Conversions",
    featured: true,
    youtubeId: null,
    imagePath: "/blog/pdf-to-word-template.webp",
  },
  {
    id: 7,
    title:
      "How to Rebrand Your Business Documents Without Starting From Scratch",
    description:
      "Learn how to efficiently rebrand your business documents without rebuilding everything. Discover smart strategies for updating logos, colors, and brand elements while preserving your existing document structure and saving time.",
    slug: "document-rebranding",
    date: "October 28, 2025",
    author: "Daniel Thomas",
    readingTime: "12 min",
    category: "Templates",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/rebrand.webp",
  },
  {
    id: 8,
    title: "Microsoft Word for Mac: What You Need to Know",
    description:
      "Discover the real differences between Word for Mac and Windows. Learn about missing features, VBA limitations, workarounds, and whether Word for Mac is right for your workflow.",
    slug: "microsoft-word-for-mac",
    date: "December 13, 2025",
    author: "Rochelle Robinson",
    readingTime: "11 min",
    category: "Word",
    featured: false,
    youtubeId: null,
    imagePath: "/blog/word-mac/word-to-mac.webp",
  },
];
